import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AbilityProvider } from "../components/Context/AbilityContext";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AbilityProvider scores={{ STR: 14, DEX: 14, CON: 12, INT: 10, WIS: 12, CHA: 8}}>
          {children}
        </AbilityProvider>
      </body>
    </html>
  );
}
